name: Deployment

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Use composite action (cache deps)
        uses: ./.github/action/cach-action

      - name: Lint code
        run: npm run lint
        continue-on-error: true


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4


      - name: Use composite action (cache deps)
        uses: ./.github/action/cach-action

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - name: Test code
        id: run-tests
        run: npm run test

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Use composite action (cache + install)
        uses: ./.github/action/cach-action

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: deploy site 
        id: deploy
        uses: ./.github/action/Docker-action
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with: 
            bucket-name: githupction-2552003
            directory: ./dist


      - name: Show files
        run: ls -la

      - name: print url
        run: echo "Deployed to ${{ steps.deploy.outputs.deployment-url }}"